import Head from "next/head";
import { FC } from "react";

interface Props{}

export const Meta: FC<Props> = () => {
    return (
      <>
      <Head>
        <title>カクテル検索くん</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cocktail.png" />
      </Head>
        
      </>
    );
  };